ALTER TRIGGER ANTES_ELIMINAR_MOVIMIENTOS INACTIVE;
ALTER TRIGGER ANTES_ELIMINAR_KARDEX INACTIVE;
ALTER TRIGGER ANTES_ACTUALIZAR_DOCUMENTOS_CAB_0 INACTIVE;
ALTER TRIGGER ANTES_ACTUALIZAR_DOCUMENTOS_CAB_1 INACTIVE;
ALTER TRIGGER DESPUES_ACTUALIZAR_DOCUMENTOS_CAB INACTIVE;
ALTER TRIGGER DESPUES_ACTUALIZAR_DOCUMENTOS_CAB_02 INACTIVE;
ALTER TRIGGER ANTES_ACTUALIZAR_DOCUMENTOS_DET INACTIVE;
ALTER TRIGGER ANTES_ACTUALIZAR_COMPR010_0 INACTIVE;
ALTER TRIGGER ANTES_ACTUALIZAR_COMPR010_1 INACTIVE;
ALTER TRIGGER DESPUES_ACTUALIZAR_COMPR010 INACTIVE;
ALTER TRIGGER ANTES_ELIMINAR_COMPR010_0 INACTIVE;
ALTER TRIGGER ANTES_ELIMINAR_COMPR010_1 INACTIVE;
ALTER TRIGGER DESPUES_ELIMINAR_COMPR010 INACTIVE;
ALTER TRIGGER DESPUES_INSERTAR_CLIENTE INACTIVE;
ALTER TRIGGER ANTES_ELIMINAR_CLIENTE INACTIVE;

DELETE FROM MOVIMIENTOS WHERE STATUS=FALSE;
DELETE FROM KARDEX WHERE STATUS=FALSE;

DELETE FROM ARTICULOS_CLASE WHERE CODART='';
DELETE FROM ARTICULO_ALMACEN WHERE CODART='';
DELETE FROM ARTICULO_ESPECIFICACION WHERE CODART='';
DELETE FROM ARTICULO_INTERMEDIO WHERE CODART='';
DELETE FROM ARTICULOS_ALMACEN WHERE CODART='';
DELETE FROM ARTICULOS_ALMACEN_CODADD WHERE CODART='';
DELETE FROM ARTICULOS_CLASE_ALTERNATIVO WHERE CODART='';
DELETE FROM ARTICULOS_CLASE_GLOBAL WHERE CODART='';
DELETE FROM ARTICULOS_COMBOS WHERE CODART='';
DELETE FROM ARTICULOS_COSTO WHERE CODART='';
DELETE FROM ARTICULOS_COSTO_CODADD WHERE CODART='';
DELETE FROM ARTICULOS_COSTO_REPOSICION WHERE CODART='';
DELETE FROM ARTICULOS_DEPREALT WHERE CODART='';
DELETE FROM ARTICULOS_DEPRECIACION WHERE CODART='';
DELETE FROM ARTICULOS_DETRACCION WHERE CODART='';
DELETE FROM ARTICULOS_EAN WHERE CODART='';
DELETE FROM ARTICULOS_EXONERADO WHERE CODART='';
DELETE FROM ARTICULOS_GLOSA WHERE CODART='';
DELETE FROM ARTICULOS_IMAGEN WHERE CODART='';
DELETE FROM ARTICULOS_ISC WHERE CODART='';
DELETE FROM ARTICULOS_MOVIMIENTO WHERE CODART='';
DELETE FROM ARTICULOS_MUEBLES WHERE CODART='';
DELETE FROM ARTICULOS WHERE CODART='';
DELETE FROM CLIENTE_ARTICULOS_CLASE WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTE_BANCOS WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTE_CLASE  WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTE_CODPAG WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTE_TPERSONA WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTECONTACTO_CLASE WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTECONTACTO WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTES_ALMACEN_CLASE WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTES_CREDITO_LOG WHERE CODCLI='' OR CODCLI IS NULL;
DELETE FROM CLIENTES_ESPECIFICACION WHERE CODCLI='' OR CODCLI IS NULL;

INSERT INTO CLIENTE(CODCLI,RAZONC) VALUES ('ND','CLIENTE NO DEFINIDO');
UPDATE DOCUMENTOS_CAB SET CODCLI='ND' WHERE CODCLI IS NULL OR CODCLI='';
UPDATE COMPR010 SET CODPRO='ND' WHERE CODPRO IS NULL OR CODPRO='';
UPDATE PROV105 SET CODCLI='ND' WHERE CODCLI IS NULL OR CODCLI='';   
UPDATE DCTA105 SET CODCLI='ND' WHERE CODCLI IS NULL OR CODCLI='';

DELETE FROM CLIENTE WHERE CODCLI='' OR CODCLI IS NULL;

UPDATE SUCURSAL SET HORENT=NULL;
UPDATE TDOCCOBRANZA_CLASE SET MONEDA='XXX' WHERE MONEDA IS NULL OR MONEDA='' OR MONEDA='   ';
UPDATE TDOCUME_CLASES SET MONEDA='PEN' WHERE MONEDA IS NULL OR MONEDA='   ';
UPDATE PCUENTAS SET CODTANA = NULL;
DELETE FROM CLIENTECONTACTO_CLASE WHERE CODIGO IS NULL OR CODIGO='';
UPDATE MATERIALES_ESTANDAR SET CODADD01PRO = ' ' WHERE CODADD01PRO IS NULL OR CODADD01PRO='';
UPDATE MATERIALES_ESTANDAR SET CODADD02PRO = ' ' WHERE CODADD02PRO IS NULL OR CODADD02PRO='';
DELETE FROM PERMISOS WHERE CODUSER IS NULL OR CODUSER='';
DELETE FROM TIPOTAREA WHERE CODTTA IS NULL OR CODTTA='';
DELETE FROM ACCIONTAREA WHERE CODACC IS NULL;
DELETE FROM ARTICULOS_ALMACEN AA WHERE NOT EXISTS (SELECT 1 FROM ALMACEN A WHERE A.TIPINV = AA.TIPINV AND A.CODALM = AA.CODALM);
DELETE FROM ARTICULOS_CLASE AC WHERE NOT EXISTS (SELECT 1 FROM ARTICULOS A WHERE A.TIPINV = AC.TIPINV AND A.CODART = AC.CODART);
DELETE FROM CLIENTE_CLASE CC WHERE NOT EXISTS (SELECT 1 FROM CLIENTE C WHERE C.CODCLI = CC.CODCLI);
DELETE FROM CLIENTE_CODPAG CP WHERE NOT EXISTS (SELECT 1 FROM CLIENTE C WHERE C.CODCLI = CP.CODCLI);
DELETE FROM DOCUMENTOS_CAB_LOG WHERE TOTBRU>4000000;
DELETE FROM ARTICULOS_COSTO_REPOSICION WHERE CODADD01 IS NULL OR CODADD01='';
DELETE FROM COMPR010 C10 WHERE NOT EXISTS (SELECT 1 FROM CLIENTE C WHERE C.CODCLI = C10.CODPRO) AND SITUAC <> 2;
INSERT INTO CLIENTE (CODCLI, RAZONC) ( SELECT DISTINCT C10.CODPRO, 'PROVEEDOR ELIMINADO' FROM COMPR010 C10 WHERE NOT EXISTS (SELECT 1 FROM CLIENTE C WHERE C.CODCLI = C10.CODPRO) AND SITUAC = 2 );
INSERT INTO CLIENTE (CODCLI, RAZONC) ( SELECT DISTINCT P5.CODCLI, 'PROVEEDOR ELIMINADO' FROM PROV105 P5 WHERE NOT EXISTS (SELECT 1 FROM CLIENTE C WHERE C.CODCLI = P5.CODCLI));

UPDATE DOCUMENTOS SET CODSUC=1 WHERE CODSUC IN (0,999);

BATCH START;
UPDATE DOCUMENTOS_DET SET OBSERV=(SUBSTR2(OBSERV,1,1000)) WHERE FCREAC BETWEEN '2025-01-01' AND '2025-12-31';
BATCH EXECUTE;

BATCH START;
UPDATE DOCUMENTOS_DET SET OBSERV=NULL;
BATCH EXECUTE;

BATCH START;
UPDATE DOCUMENTOS_CAB SET OBSERV=(SUBSTR2(OBSERV,1,1000)) WHERE FCREAC BETWEEN '2000-01-01' AND '2024-01-01';
BATCH EXECUTE;

UPDATE DOCUMENTOS_DET SET OBSERV=(SUBSTR2(OBSERV,1,1000));
UPDATE DOCUMENTOS_CAB SET OBSERV=(SUBSTR2(OBSERV,1,1000));


-- UPDATE COMPR010 SET CODPRO = '10096730999' WHERE CODPRO = '10096730999 ';
-- UPDATE COMPR010 SET CODPRO = '20508925574' WHERE CODPRO = '20508925574 ';
-- UPDATE COMPR010 SET CODPRO = '20376638082' WHERE CODPRO = '20376638082 ';
-- UPDATE PROV105 SET CODCLI = '10096730999' WHERE CODCLI = '10096730999 ';
-- UPDATE PROV105 SET CODCLI = '20508925574' WHERE CODCLI = '20508925574 ';
-- UPDATE PROV105 SET CODCLI = '20376638082' WHERE CODCLI = '20376638082 ';